version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: dbassetscontrol
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
volumes:
  postgres_data:
